# Generated by Django 3.0.7 on 2020-08-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roughcast", "0003_auto_20200817_0430"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PublisherMembership",
            new_name="TeamMembership",
        ),
        migrations.RenameModel(
            old_name="Publisher",
            new_name="Team",
        ),
    ]
