# Generated by Django 3.0.7 on 2020-08-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roughcast", "0004_auto_20200817_0431"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
