# Generated by Django 3.0.7 on 2020-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughcast', '0005_auto_20200820_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaTestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
