# Generated by Django 3.1 on 2020-08-28 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


def forwards(apps, schema_editor):
    Subscribable = apps.get_model("roughcast", "Subscribable")
    Team = apps.get_model("roughcast", "Team")
    Game = apps.get_model("roughcast", "Game")

    for team in Team.objects.all():
        team.subscribable = Subscribable.objects.create()
        team.save()

    for game in Game.objects.all():
        game.subscribable = Subscribable.objects.create()
        game.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("roughcast", "0008_auto_20200827_2332"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inappnotification",
            name="edited_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inappnotification",
            name="id",
            field=hashid_field.field.HashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                min_length=7,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subscribable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roughcast.subscribable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="subscribable",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="roughcast.subscribable",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="subscribable",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="roughcast.subscribable",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="game",
            name="subscribable",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="roughcast.subscribable",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="team",
            name="subscribable",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="roughcast.subscribable",
            ),
            preserve_default=False,
        ),
    ]
