# Generated by Django 3.1 on 2020-08-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roughcast', '0009_auto_20200828_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
