# Generated by Django 3.1.1 on 2020-09-24 01:32

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models

ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"


class Migration(migrations.Migration):

    dependencies = [
        ("roughcast", "0011_inappnotification_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamInvite",
            fields=[
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet=ALPHABET,
                        min_length=7,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("to_email", models.EmailField(max_length=254)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="roughcast.team"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
