# Generated by Django 3.1.1 on 2020-09-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roughcast", "0012_teaminvite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="default_visible_to",
        ),
        migrations.RemoveField(
            model_name="version",
            name="visible_to",
        ),
    ]
