# Generated by Django 3.1.1 on 2020-10-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roughcast", "0013_auto_20200927_2359"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="default_is_public",
            field=models.BooleanField(default=False),
        ),
    ]
